server:
  port: 6002
spring:
  application:
    name: node07-provider-6002
  zipkin:
    base-url: http://localhost:7003
  sleuth:
    sampler:
      # 数据 100% 上传
      percentage: 1.0
eureka:
  instance:
    hostname: provider-6001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://registry01.com:7001/eureka/